#!/usr/bin/env bash 

# set parameters for FASTQ and quant storing
STAR_INDEX="${HOME}"/cancer_project/ngs_preprocess/reference/hg38_star
TIME_OUT="${HOME}"/cancer_project/ngs_preprocess/scripts/exploratory/time.log
INPUT="${HOME}"/cancer_project/ngs_preprocess/2_trimmed
OUT="${HOME}"/cancer_project/ngs_preprocess/3_mapping


# run the same sample mutiple times in different threads
for STAR_THREADS in {8,8,8,8,11,12,12,12,16,16,16,20,20,20,22,22,22}; do

    # a warm-up run and then triplicate runs 

    # run the sample ~30 million paired-end reads
    f1="${INPUT}/SRR15852393_trimmed_1.fastq.gz"
    f2="${f1/_1.fastq.gz/_2.fastq.gz}"
    BASENAME1="$(basename "${f1}" "_trimmed_1.fastq.gz")"

    if [[ -f "${f2}" ]]; then
        echo "Running STAR mapping for sample: ${BASENAME1} with ${STAR_THREADS} threads"
        SECONDS=0
        
        # delete and create output folder - ignore if it does not exist
        rm -rf -- "${OUT}"/"${BASENAME1}_test"
        mkdir -p -- "${OUT}"/"${BASENAME1}_test"
        STAR --runThreadN "${STAR_THREADS}" \
             --genomeDir "${STAR_INDEX}" \
             --readFilesIn "${f1}" "${f2}" \
             --outFileNamePrefix "${OUT}/${BASENAME1}_test/${BASENAME1}_" \
             --readFilesCommand zcat \
             --outSAMtype BAM SortedByCoordinate \
             --quantMode TranscriptomeSAM GeneCounts
        
        if [[ $? -eq 0 ]]; then
            echo "$(date) | STAR-30m | ${STAR_THREADS} | $SECONDS seconds" >> "${TIME_OUT}"
            echo "Done and deleting output folder"
        else
            echo "$(date) | STAR-30m | ${STAR_THREADS} | $SECONDS seconds FAILED" >> "${TIME_OUT}"

        fi
    else
        exit 1
    fi

    # wait for a minute before next run
    sleep 60 

# delete once all done 
rm -rf -- "${OUT}"/"${BASENAME1}_test"
done

